### ISSUE TITLE
[1.12.2] upgrade: Cart Modifier for the assembler not working as intended, can eat carts and a question

### ISSUE THREAD

**Issue by DietmarKrause** [modmuss50/SC2#94] opened 2017-09-26 05:39 UTC
I am fairly new to Steve carts. I play it within the modpack All the mods 3, build a tree farm with it with success. I had two problems yesterday: first a question: It seems, that the wood cutter needs diamonds to get rapaired, Yesterday the cutter was at rougly 68% so i decided to try a repair, inserted diamand into the aprpriate slot but nothing happens . There is a message instead, that the machine is quit good and i should remove the diamands. Can one repair the wood cutter only when it is broken completely? 
Then the main problem. I had a problem mounting the Upgrade: Cart modifier to the Assember. From time to time it will not mount, instead it apears on a side of a ghost block right in front of the assember, but not on the appropriat side of that block (it fits in a 90% angle to the block, like a fence for example). If you have managed to mount it the right way after a few tries, the cart inserted in the upgrade is not shown in the assembler at all. After a few tries the upgrade eats the cart, i had somehow managed to put it in the wrong inventory right below the slot it should be in, after dismounting the upgrade the cart was gone. The Upgrade: cart modifier seems to be broken

**Comment by DietmarKrause** [comment] 2017-09-26 05:45
https://github.com/AllTheMods/ATM-3/issues/174

**Comment by modmuss50** [comment] 2017-10-08 19:46
duplicate of #61

**Closed as completed by modmuss50** 2017-10-08 19:46 UTC
